"""PlannerWriteMiddleware — answer a planner write with the route (OPEN-100).

**The defect.** Run `d8f742805b9b` spent 430.9 s -- 42% of all its model time
-- on three model calls emitting 4932, 5540 and 4636 output tokens each:
complete HTML documents, generated by the PLANNER, for a `write_file` tool
`PLANNER_FS_TOOLS` does not grant it and must not. Two of the three reached
the tool and were answered by langgraph's tool-list echo:

    Error: write_file is not a valid tool, try one of
      [ls, read_file, glob, grep, task, record_fact]

**The absence of the tool is correct; the answer to it was not.** That echo
says what the model cannot do and nothing about what it should, and the model
read it perfectly -- debug line 140, in its own words: *"I notice there's no
`write_file` tool available in this environment. Let me check what tools are
available and provide the HTML content to the user."* It then invented
`task {'pattern': 'create file'}`. It was not disobeying; it was looking for
a route, and there was none to find. **This is OPEN-95's argument one agent
up**: a refusal that does not carry the correction is a refusal the model
answers by re-trying.

Option A of that item bounds the stage so this cannot run for ever. This is
the other half: the model stops trying.

**It names only tools the stage actually holds.** `_tools_for_stage` gives
clarify `record_fact`/`ask_user`, architect `record_fact`, and breakdown
`add_tasks`/`drop_task`/`read_ledger` -- with NO `record_fact`. A fixed
sentence naming `record_fact` would advertise an absent tool to the breakdown
stage, which is OPEN-15, and is the defect OPEN-101 is filed on one surface
over. `machine_paths.py` already carries this rule ("it names the tool the
agent actually has"); this is the same rule with a different tool list.

**Planner stack only.** The coder and tester hold `write_file` legitimately
and this sentence would be false on their stacks -- and would eat the run's
deliverable. `tests/test_subagents_build.py` pins its absence there.

**Depends on an upstream property, which is pinned.** langgraph defers
tool-name validation into `_execute_tool_sync` specifically "to allow
interceptors to short-circuit requests for unregistered tools"
(`langgraph/prebuilt/tool_node.py:1031-1033`), so `wrap_tool_call` sees a
call to a tool that was never registered, with `request.tool` None. If that
ever changes, this middleware silently stops firing --
`tests/test_deepagents_contract.py` is where that reopens.
"""

from __future__ import annotations

import logging
from typing import Any

from langchain.agents.middleware.types import AgentMiddleware
from langchain_core.messages import ToolMessage

logger = logging.getLogger(__name__)

PLANNER_WRITE_NOTICE = "planner-write"
"""The `name` on the NOTICE, and what a maintainer greps `debug-<id>.jsonl`
for. One spelling, as a module constant (`CLAUDE.md` §8a)."""

# The write tools the planner does not have. `execute` is deliberately
# absent: it is missing from PLANNER_FS_TOOLS too, but "the coder writes the
# file" is the wrong correction for a command, and a refusal carrying a wrong
# route is worse than upstream's echo. `task` is absent because
# DelegationGuardMiddleware already owns it.
_WRITE_TOOLS = frozenset({"write_file", "edit_file", "delete"})

# What to say, given what the stage can actually do instead. Ordered: a stage
# holding both is told about the more specific one first.
_ROUTES = (
    (
        "add_tasks",
        "Declare the work with `add_tasks` and let the coder write it -- a task "
        "saying what the file must contain is the whole of your job here.",
    ),
    (
        "record_fact",
        "Record the decision with `record_fact` -- what the file is for, what it "
        "must contain, and why -- and the coder will write it from that.",
    ),
)

_REJECTED = (
    "REJECTED: `{path}` was not written. The planner plans; it does not write "
    "files, and no stage of it has a write tool.\n\n"
    "{route}\n\n"
    "Do not generate the file's contents anywhere -- not in a tool argument and "
    "not in your reply. Describe what it must contain; the coder writes it, "
    "runs the gate against it, and fixes it. Nothing you produce here can reach "
    "disk."
)

_ROUTELESS = (
    "This stage cannot declare the work either. Finish what it is for and stop; "
    "the next stage declares the work and the coder writes the file."
)


class PlannerWriteMiddleware(AgentMiddleware):
    """Answer a planner `write_file`/`edit_file`/`delete` with the route.

    Answers rather than annotating, for `fix_write_params.py`'s stated
    reason inverted: there are no bytes to annotate. The tool does not exist
    on this stack, so letting the call through only reaches upstream's echo,
    which is the thing being replaced.
    """

    def __init__(
        self,
        stage_tools: tuple[str, ...] | frozenset[str] = (),
        *,
        role: str = "planner",
        usage: Any = None,
        trace: Any = None,
    ) -> None:
        super().__init__()
        # NOT `self.tools`. `AgentMiddleware.tools` is upstream's list of
        # tools a middleware CONTRIBUTES to the agent (types.py:150), and
        # langchain registers every entry of it -- so assigning tool NAMES
        # there hands `ToolNode` a set of strings and the agent fails to
        # build. The name this middleware reads is not the name upstream
        # writes.
        self.stage_tools = frozenset(stage_tools)
        self.role = role
        self.usage = usage
        self.trace = trace

    def _route(self) -> str:
        """The correction, naming a tool this stage HAS (OPEN-15).

        Declines to name one rather than naming a wrong one: a stage holding
        neither is told to finish and stop, which is true of every stage.
        """
        for name, sentence in _ROUTES:
            if name in self.stage_tools:
                return sentence
        return _ROUTELESS

    def _announce(self, path: str) -> None:
        """Count and say that a planner write was refused (`TODO.md` lesson 5).

        Both halves swallow their own failure: a run that did its work must
        not be reported failed because a log line could not be written
        (`CLAUDE.md` §8a).
        """
        try:
            if self.usage is not None:
                self.usage.record_planner_write_refused(self.role)
        except Exception:  # noqa: BLE001 - bookkeeping may never end a run
            logger.debug("planner write refusal not counted", exc_info=True)
        try:
            if self.trace is not None:
                self.trace.notice(
                    f"refused a planner write to {path}: the planner has no write "
                    "tool and the coder writes the files",
                    role=self.role,
                    name=PLANNER_WRITE_NOTICE,
                )
        except Exception:  # noqa: BLE001 - same rule
            logger.debug("planner write refusal not announced", exc_info=True)

    def _refusal(self, request):
        """A ToolMessage carrying the route, or None to let the call through."""
        call = getattr(request, "tool_call", None) or {}
        name = call.get("name", "")
        if name not in _WRITE_TOOLS:
            return None

        args = call.get("args") or {}
        path = args.get("file_path") or args.get("path") or "that file"
        self._announce(str(path))
        return ToolMessage(
            content=_REJECTED.format(path=path, route=self._route()),
            tool_call_id=call.get("id", ""),
            name=name,
            status="error",
        )

    def wrap_tool_call(self, request, handler):
        refusal = self._refusal(request)
        return refusal if refusal is not None else handler(request)

    async def awrap_tool_call(self, request, handler):
        refusal = self._refusal(request)
        return refusal if refusal is not None else await handler(request)


__all__ = ["PLANNER_WRITE_NOTICE", "PlannerWriteMiddleware"]
